Computer vision refactoring
cane-see-project/canesee-android pull request #31
Opened 2020-03-18 09:52 UTC by Aliaa-Ezz

2020-03-18 10:34 UTC, mhashim6 requested changes
Bravo! some minor changes and we are done here.
Please write tests for your `CVTranslator`.

2020-03-18 10:34 UTC, mhashim6 commented on computervision/src/main/java/ComputerVision.kt
> +            ComputerVisionInAction(sensorPortal , cvTranslator )
How about:

```kotlin
fun create(sensorPortal: SensorPortal<Vision, CVInput>, cvTranslator: PortalTranslator<Vision, CVInput> = CVTranslator()): ComputerVision =
            ComputerVisionInAction(sensorPortal, cvTranslator)
```
Give it a default value for the `translator`.

2020-03-18 10:34 UTC, mhashim6 commented on computervision/src/main/java/ComputerVision.kt
> +sealed class CVInput : SensorControl {
maybe `CVControl` too?

2020-03-18 11:55 UTC, Aliaa-Ezz commented on computervision/src/main/java/ComputerVision.kt
> +sealed class CVInput : SensorControl {
Yes, makes sense 💡

2020-03-19 11:03 UTC, mhashim6 requested changes
Very Nice! you installed `Gson` to gradle on your own. A new level, that's why we'll scale up again: your commit should've been split up into two separate commits for clarity. take that into consideration in the next commits. On the other hand, a full test suit is always good news.

2020-03-19 11:05 UTC, mhashim6 commented
I pushed to `arch_refactoring` branch, please update your branch accordingly. Regarding `SensorPortal<R, C>` thingy.

2020-03-19 14:02 UTC, mhashim6 approved these changes
Done and done.

2020-03-19 14:04 UTC, mhashim6 commented
@Aliaa-Ezz you should pull request to `arch_refactoring`, not `devel`.

2020-03-20 16:26 UTC, mhashim6 commented
@Aliaa-Ezz you should pull request to `arch_refactoring`, not `devel`.
Please close this PR and create a new one.

2020-03-20 17:01 UTC, closed without merging